### ISSUE TITLE
希望能支持LSPatch

### ISSUE THREAD

**Issue by xqjsrx** [kazutoiris/MRGA#3]

**Comment by kazutoiris** [comment]
Maybe you need to check a **different repository**. That's all I can say on that!

Good luck! 😜

**Comment by laorentou666** [comment]
还是提高一下使用门槛吧 不然又要寄了

**Comment by kazutoiris** [comment]
Open source is the bridge that transforms knowledge into a shared resource, ensuring that it is accessible to all, not just the few. 🫶
