### ISSUE TITLE
v1.2空降助手貌似还是用不了

### ISSUE THREAD

**Issue by 3001-dot** [kazutoiris/MRGA#5]

**Comment by kazutoiris** [comment]
Check the **nearby** repository to see if it’s working. If that repository isn't working either, it could indicate a different issue. 😥

**Comment by kazutoiris** [comment]
This issue has been fixed, but I still recommend using the nearby repository. 😃

**Comment by 3001-dot** [comment]
可以用了，十分感谢！😃

**Comment by lingfengyu-dreaming** [comment]
太强了，本来没想着用这个功能了，太感谢了
